//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RubyEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Employee_Id { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Email { get; set; }
        public string Building { get; set; }
        public string Room { get; set; }
        public string Phone { get; set; }
        public int Warden_Ind { get; set; }
        public int Active_Ind { get; set; }
    }
}
