//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RubyEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ref_Event_Type
    {
        public int Event_Type_Id { get; set; }
        public string Emergency_Type { get; set; }
        public string Status { get; set; }
        public int Active_Ind { get; set; }
    }
}
